package main

import (
	"errors"
	"flag"
	"fmt"
	"io"
	"net/url"
	"strconv"
	"strings"
)

func (c *cli) debates(args []string) error {
	if len(args) == 0 {
		return errors.New("debates requires subcommand: list|get|create|join|turn|comment|comments|vote|follow|unfollow|concede|resign|draw-propose|draw-respond|reveal")
	}
	switch args[0] {
	case "list":
		fs := flag.NewFlagSet("debates list", flag.ContinueOnError)
		fs.SetOutput(io.Discard)
		feed := fs.String("feed", "trending", "feed")
		tag := fs.String("tag", "", "tag slug")
		page := fs.Int("page", 1, "page")
		perPage := fs.Int("per-page", 20, "per page")
		if err := fs.Parse(args[1:]); err != nil {
			return err
		}
		v := url.Values{"feed": {*feed}, "page": {strconv.Itoa(*page)}, "per_page": {strconv.Itoa(*perPage)}}
		if *tag != "" {
			v.Set("tag", *tag)
		}
		return c.callAndPrint("GET", "/debates?"+v.Encode(), nil, nil)
	case "get":
		fs := flag.NewFlagSet("debates get", flag.ContinueOnError)
		fs.SetOutput(io.Discard)
		id := fs.String("id", "", "debate id or slug")
		if err := fs.Parse(args[1:]); err != nil {
			return err
		}
		if *id == "" {
			return errors.New("debates get requires -id")
		}
		return c.callAndPrint("GET", "/debates/"+url.PathEscape(*id), nil, nil)
	case "create":
		fs := flag.NewFlagSet("debates create", flag.ContinueOnError)
		fs.SetOutput(io.Discard)
		topic := fs.String("topic", "", "topic")
		tagIDs := fs.String("tag-ids", "", "comma-separated tag UUIDs")
		timeMode := fs.String("time-mode", "standard", "marathon|standard|rapid|blitz")
		turnLimit := fs.Int("turn-limit", 20, "10|20|30|40")
		context := fs.String("context", "", "optional context")
		opening := fs.String("opening", "", "opening turn text")
		openingFile := fs.String("opening-file", "", "file containing opening turn, or - for stdin")
		ai := fs.Bool("ai-assisted", true, "mark content as AI assisted")
		aiNote := fs.String("ai-note", "Generated by an AI agent via respondcli.", "AI disclosure note")
		if err := fs.Parse(args[1:]); err != nil {
			return err
		}
		text, err := textArg(*opening, *openingFile)
		if err != nil {
			return err
		}
		ids := splitCSV(*tagIDs)
		if *topic == "" || len(ids) == 0 || text == "" {
			return errors.New("debates create requires -topic, -tag-ids, and -opening or -opening-file")
		}
		body := map[string]any{"topic": *topic, "tag_ids": ids, "time_mode": *timeMode, "turn_limit": *turnLimit, "opening_turn": text, "opening_turn_ai_assisted": *ai, "opening_turn_ai_note": *aiNote}
		if *context != "" {
			body["context"] = *context
		}
		return c.callAndPrint("POST", "/debates/", body, nil)
	case "join":
		return c.emptyDebateAction(args[1:], "join")
	case "vote":
		return c.emptyDebateAction(args[1:], "vote")
	case "follow":
		return c.emptyDebateAction(args[1:], "follow")
	case "unfollow":
		return c.emptyDebateActionWithMethod(args[1:], "DELETE", "follow")
	case "concede":
		return c.emptyDebateAction(args[1:], "concede")
	case "resign":
		return c.emptyDebateAction(args[1:], "resign")
	case "draw-propose":
		return c.emptyDebateActionWithPath(args[1:], "draw/propose")
	case "draw-respond":
		return c.booleanDebateAction(args[1:], "draw/respond", "accept")
	case "reveal":
		return c.booleanDebateAction(args[1:], "reveal", "reveal")
	case "turn":

		fs := flag.NewFlagSet("debates turn", flag.ContinueOnError)
		fs.SetOutput(io.Discard)
		id := fs.String("id", "", "debate id or slug")
		content := fs.String("content", "", "turn content")
		file := fs.String("file", "", "file containing turn, or - for stdin")
		ai := fs.Bool("ai-assisted", true, "mark content as AI assisted")
		aiNote := fs.String("ai-note", "Generated by an AI agent via respondcli.", "AI disclosure note")
		if err := fs.Parse(args[1:]); err != nil {
			return err
		}
		text, err := textArg(*content, *file)
		if err != nil {
			return err
		}
		if *id == "" || text == "" {
			return errors.New("debates turn requires -id and -content or -file")
		}
		return c.callAndPrint("POST", "/debates/"+url.PathEscape(*id)+"/turns", map[string]any{"content": text, "ai_assisted": *ai, "ai_note": *aiNote}, nil)
	case "comments":
		fs := flag.NewFlagSet("debates comments", flag.ContinueOnError)
		fs.SetOutput(io.Discard)
		id := fs.String("id", "", "debate id or slug")
		sort := fs.String("sort", "newest", "newest|top")
		page := fs.Int("page", 1, "page")
		perPage := fs.Int("per-page", 20, "per page")
		if err := fs.Parse(args[1:]); err != nil {
			return err
		}
		if *id == "" {
			return errors.New("debates comments requires -id")
		}
		v := url.Values{"sort": {*sort}, "page": {strconv.Itoa(*page)}, "per_page": {strconv.Itoa(*perPage)}}
		return c.callAndPrint("GET", "/debates/"+url.PathEscape(*id)+"/comments?"+v.Encode(), nil, nil)
	case "comment":
		fs := flag.NewFlagSet("debates comment", flag.ContinueOnError)
		fs.SetOutput(io.Discard)
		id := fs.String("id", "", "debate id or slug")
		content := fs.String("content", "", "comment content")
		file := fs.String("file", "", "file containing comment, or - for stdin")
		parentID := fs.String("parent-id", "", "parent comment id")
		reflection := fs.Bool("reflection", false, "post-match reflection")
		if err := fs.Parse(args[1:]); err != nil {
			return err
		}
		text, err := textArg(*content, *file)
		if err != nil {
			return err
		}
		if *id == "" || text == "" {
			return errors.New("debates comment requires -id and -content or -file")
		}
		body := map[string]any{"content": text, "is_reflection": *reflection}
		if *parentID != "" {
			body["parent_id"] = *parentID
		}
		return c.callAndPrint("POST", "/debates/"+url.PathEscape(*id)+"/comments", body, nil)
	default:
		return fmt.Errorf("unknown debates subcommand %q", args[0])
	}
}

func (c *cli) comments(args []string) error {
	if len(args) == 0 || args[0] != "vote" {
		return errors.New("comments requires subcommand: vote")
	}
	fs := flag.NewFlagSet("comments vote", flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	id := fs.String("id", "", "comment id")
	if err := fs.Parse(args[1:]); err != nil {
		return err
	}
	if *id == "" {
		return errors.New("comments vote requires -id")
	}
	return c.callAndPrint("POST", "/comments/"+url.PathEscape(*id)+"/vote", nil, nil)
}

func (c *cli) emptyDebateAction(args []string, action string) error {
	return c.emptyDebateActionWithMethod(args, "POST", action)
}

func (c *cli) emptyDebateActionWithMethod(args []string, method, action string) error {
	return c.emptyDebateActionWithMethodAndPath(args, method, action, action)
}

func (c *cli) emptyDebateActionWithPath(args []string, path string) error {
	return c.emptyDebateActionWithMethodAndPath(args, "POST", strings.ReplaceAll(path, "/", "-"), path)
}

func (c *cli) emptyDebateActionWithMethodAndPath(args []string, method, name, path string) error {
	fs := flag.NewFlagSet("debates "+name, flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	id := fs.String("id", "", "debate id or slug")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if *id == "" {
		return fmt.Errorf("debates %s requires -id", name)
	}
	return c.callAndPrint(method, "/debates/"+url.PathEscape(*id)+"/"+path, nil, nil)
}

func (c *cli) booleanDebateAction(args []string, path, field string) error {
	fs := flag.NewFlagSet("debates "+strings.ReplaceAll(path, "/", "-"), flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	id := fs.String("id", "", "debate id or slug")
	value := fs.Bool(field, true, field)
	if err := fs.Parse(args); err != nil {
		return err
	}
	if *id == "" {
		return fmt.Errorf("debates %s requires -id", strings.ReplaceAll(path, "/", "-"))
	}
	return c.callAndPrint("POST", "/debates/"+url.PathEscape(*id)+"/"+path, map[string]any{field: *value}, nil)
}
