import Link from "next/link"
import type { AppLocale } from "@/i18n/config"
import type { InviteRecord, NotificationSettings } from "@/lib/settings-api"
import type { BlockedUser } from "@/lib/users"
import { Button } from "@/components/ui/button"

export const DEFAULT_NOTIFICATION_SETTINGS: NotificationSettings = {
  email_your_turn: true,
  email_debate_joined: true,
  email_debate_ended: false,
  email_turn_expiring: true,
  email_seat_open: false,
  email_draw_proposed: true,
}

export const NOTIFICATION_FIELDS: Array<keyof NotificationSettings> = [
  "email_your_turn",
  "email_debate_joined",
  "email_debate_ended",
  "email_turn_expiring",
  "email_seat_open",
  "email_draw_proposed",
]

type T = (key: string, values?: Record<string, unknown>) => string

type StatusLineProps = { message?: string | null; error?: string | null }
function StatusLine({ message, error }: StatusLineProps) {
  return <>{message && <span className="text-[12px] text-emerald-700 font-sans">{message}</span>}{error && <span className="text-[12px] text-[var(--error)] font-sans">{error}</span>}</>
}

export function SettingsHeader({ t }: { t: T }) {
  return <section className="bg-[var(--bg-surface)] border border-[var(--border-default)] rounded-lg p-5 sm:p-6"><h1 className="text-[18px] sm:text-[20px] font-semibold text-[var(--text-primary)] font-sans">{t("title")}</h1><p className="mt-1 text-[13px] text-[var(--text-secondary)] font-sans">{t("subtitle")}</p></section>
}

export function ProfileSettingsSection({ bio, bioCount, defaultReveal, error, message, saving, t, onBioChange, onDefaultRevealChange, onSave }: { bio: string; bioCount: number; defaultReveal: boolean; error: string | null; message: string | null; saving: boolean; t: T; onBioChange: (value: string) => void; onDefaultRevealChange: (value: boolean) => void; onSave: () => void }) {
  return <section className="bg-[var(--bg-surface)] border border-[var(--border-default)] rounded-lg p-5 sm:p-6"><h2 className="text-[15px] font-semibold text-[var(--text-primary)] font-sans">{t("profile.title")}</h2><div className="mt-4 space-y-4"><label className="block"><span className="text-[12px] font-medium text-[var(--text-secondary)] font-sans">{t("profile.bio")}</span><textarea value={bio} onChange={(event) => onBioChange(event.target.value)} maxLength={200} rows={3} className="mt-1 w-full rounded-md border border-[var(--border-default)] bg-[var(--bg-surface)] px-3 py-2 text-[14px] text-[var(--text-secondary)] font-sans" /><span className="mt-1 block text-[11px] text-[var(--text-muted)] font-sans">{bioCount}/200</span></label><label className="flex items-center gap-2 text-[13px] text-[var(--text-secondary)] font-sans"><input type="checkbox" checked={defaultReveal} onChange={(event) => onDefaultRevealChange(event.target.checked)} className="h-4 w-4 rounded border-[var(--border-default)]" />{t("profile.revealDefault")}</label></div><div className="mt-4 flex items-center gap-3"><button type="button" onClick={onSave} disabled={saving} className="px-3 py-2 rounded-md text-[12px] font-medium font-sans bg-[var(--text-primary)] text-[var(--bg-primary)] hover:opacity-90 disabled:opacity-60">{saving ? t("saving") : t("save")}</button><StatusLine message={message} error={error} /></div></section>
}

export function LanguageSettingsSection({ currentUserLocale, error, locale, message, saving, t, onLocaleChange, onSave }: { currentUserLocale?: AppLocale | null; error: string | null; locale: AppLocale; message: string | null; saving: boolean; t: T; onLocaleChange: (value: AppLocale) => void; onSave: () => void }) {
  return <section className="bg-[var(--bg-surface)] border border-[var(--border-default)] rounded-lg p-5 sm:p-6"><h2 className="text-[15px] font-semibold text-[var(--text-primary)] font-sans">{t("language.title")}</h2><p className="mt-1 text-[12px] text-[var(--text-secondary)] font-sans">{t("language.description")}</p><label className="mt-4 block max-w-xs"><span className="text-[12px] font-medium text-[var(--text-secondary)] font-sans">{t("language.label")}</span><select value={locale} onChange={(event) => onLocaleChange(event.target.value as AppLocale)} className="mt-1 w-full rounded-md border border-[var(--border-default)] bg-[var(--bg-surface)] px-3 py-2 text-[14px] text-[var(--text-primary)] font-sans"><option value="en">English</option><option value="vi">Tiếng Việt</option></select></label><div className="mt-4 flex items-center gap-3"><button type="button" onClick={onSave} disabled={saving || locale === currentUserLocale} className="px-3 py-2 rounded-md text-[12px] font-medium font-sans bg-[var(--text-primary)] text-[var(--bg-primary)] hover:opacity-90 disabled:opacity-60">{saving ? t("saving") : t("language.save")}</button><StatusLine message={message} error={error} /></div></section>
}

export function NotificationSettingsSection({ error, loading, message, saving, settings, t, onSave, onSettingsChange }: { error: string | null; loading: boolean; message: string | null; saving: boolean; settings: NotificationSettings; t: T; onSave: () => void; onSettingsChange: (settings: NotificationSettings | ((prev: NotificationSettings) => NotificationSettings)) => void }) {
  return <section className="bg-[var(--bg-surface)] border border-[var(--border-default)] rounded-lg p-5 sm:p-6"><h2 className="text-[15px] font-semibold text-[var(--text-primary)] font-sans">{t("notifications.title")}</h2>{loading ? <p className="mt-3 text-[13px] text-[var(--text-muted)] font-sans">{t("notifications.loading")}</p> : <div className="mt-4 space-y-2">{NOTIFICATION_FIELDS.map((key) => <label key={key} className="flex items-center gap-2 text-[13px] text-[var(--text-secondary)] font-sans"><input type="checkbox" checked={settings[key]} onChange={(event) => onSettingsChange((prev) => ({ ...prev, [key]: event.target.checked }))} className="h-4 w-4 rounded border-[var(--border-default)]" />{t(`notifications.fields.${key}`)}</label>)}</div>}<div className="mt-4 flex items-center gap-3"><button type="button" onClick={onSave} disabled={loading || saving} className="px-3 py-2 rounded-md text-[12px] font-medium font-sans bg-[var(--text-primary)] text-[var(--bg-primary)] hover:opacity-90 disabled:opacity-60">{saving ? t("saving") : t("save")}</button><StatusLine message={message} error={error} /></div></section>
}

export function SecuritySettingsSection({ confirmNewPassword, currentPassword, error, message, newPassword, saving, t, onConfirmNewPasswordChange, onCurrentPasswordChange, onNewPasswordChange, onSave }: { confirmNewPassword: string; currentPassword: string; error: string | null; message: string | null; newPassword: string; saving: boolean; t: T; onConfirmNewPasswordChange: (value: string) => void; onCurrentPasswordChange: (value: string) => void; onNewPasswordChange: (value: string) => void; onSave: () => void }) {
  return <section className="bg-[var(--bg-surface)] border border-[var(--border-default)] rounded-lg p-5 sm:p-6"><h2 className="text-[15px] font-semibold text-[var(--text-primary)] font-sans">{t("security.title")}</h2><div className="mt-4 grid gap-3 sm:grid-cols-3">{[["security.currentPassword", currentPassword, onCurrentPasswordChange], ["security.newPassword", newPassword, onNewPasswordChange], ["security.confirmNewPassword", confirmNewPassword, onConfirmNewPasswordChange]].map(([label, value, setter]) => <label key={label as string} className="block"><span className="text-[12px] font-medium text-[var(--text-secondary)] font-sans">{t(label as string)}</span><input type="password" value={value as string} onChange={(event) => (setter as (value: string) => void)(event.target.value)} className="mt-1 w-full rounded-md border border-[var(--border-default)] bg-[var(--bg-surface)] px-3 py-2 text-[14px] text-[var(--text-secondary)] font-sans" /></label>)}</div><div className="mt-4 flex items-center gap-3"><button type="button" onClick={onSave} disabled={saving || currentPassword.trim().length === 0 || newPassword.trim().length === 0 || confirmNewPassword.trim().length === 0} className="px-3 py-2 rounded-md text-[12px] font-medium font-sans bg-[var(--text-primary)] text-[var(--bg-primary)] hover:opacity-90 disabled:opacity-60">{saving ? t("security.updating") : t("security.changePassword")}</button><StatusLine message={message} error={error} /></div></section>
}

export function BlockedUsersSection({ blockedUsers, error, loading, t, unblockingUsername, onUnblock }: { blockedUsers: BlockedUser[]; error: string | null; loading: boolean; t: T; unblockingUsername: string | null; onUnblock: (username: string) => void }) {
  return <section className="bg-[var(--bg-surface)] border border-[var(--border-default)] rounded-lg p-5 sm:p-6"><h2 className="text-[15px] font-semibold text-[var(--text-primary)] font-sans">{t("blocked.title")}</h2><p className="mt-1 text-[12px] text-[var(--text-secondary)] font-sans">{t("blocked.description")}</p>{loading ? <p className="mt-3 text-[13px] text-[var(--text-muted)] font-sans">{t("blocked.loading")}</p> : blockedUsers.length === 0 ? <p className="mt-3 text-[13px] text-[var(--text-muted)] font-sans">{t("blocked.empty")}</p> : <div className="mt-3 divide-y divide-[var(--border-subtle)] rounded-md border border-[var(--border-default)]">{blockedUsers.map((entry) => <div key={entry.username} className="flex items-center justify-between gap-3 px-3 py-2"><div><div className="text-[13px] text-[var(--text-primary)] font-medium font-sans">@{entry.username}</div><div className="text-[11px] text-[var(--text-muted)] font-sans">{t("blocked.blockedOn", { date: new Date(entry.blocked_at).toLocaleDateString() })}</div></div><Button type="button" variant="outline" size="sm" onClick={() => onUnblock(entry.username)} disabled={unblockingUsername === entry.username}>{unblockingUsername === entry.username ? t("blocked.unblocking") : t("blocked.unblock")}</Button></div>)}</div>}{error && <div className="mt-2 text-[12px] text-[var(--error)] font-sans">{error}</div>}</section>
}

export function EmailSettingsSection({ email, emailError, emailMessage, emailPassword, emailSaving, emailVerified, newEmail, resendError, resendMessage, resendSaving, t, onEmailPasswordChange, onNewEmailChange, onResend, onSave }: { email?: string; emailError: string | null; emailMessage: string | null; emailPassword: string; emailSaving: boolean; emailVerified?: boolean; newEmail: string; resendError: string | null; resendMessage: string | null; resendSaving: boolean; t: T; onEmailPasswordChange: (value: string) => void; onNewEmailChange: (value: string) => void; onResend: () => void; onSave: () => void }) {
  return <section className="bg-[var(--bg-surface)] border border-[var(--border-default)] rounded-lg p-5 sm:p-6"><h2 className="text-[15px] font-semibold text-[var(--text-primary)] font-sans">{t("email.title")}</h2><div className="mt-3 rounded-md border border-[var(--border-default)] bg-[var(--bg-surface-alt)] px-3 py-2"><div className="text-[11px] font-medium text-[var(--text-muted)] font-sans uppercase tracking-wide">{t("email.current")}</div><div className="mt-0.5 text-[13px] text-[var(--text-primary)] font-sans">{email}{emailVerified ? <span className="ml-2 text-[11px] text-emerald-700">{t("email.verified")}</span> : <span className="ml-2 text-[11px] text-amber-700">{t("email.unverified")}</span>}</div></div>{!emailVerified && <div className="mt-3 rounded-md border border-[var(--border-default)] bg-[var(--bg-surface-alt)] px-3 py-2 flex flex-col sm:flex-row sm:items-center gap-2"><div className="text-[12px] text-[var(--text-secondary)] font-sans">{t("email.unverifiedNotice")}</div><div className="sm:ml-auto w-full sm:w-auto"><div className="flex items-center gap-3"><button type="button" onClick={onResend} disabled={resendSaving} className="text-[12px] font-semibold text-[var(--text-primary)] font-sans hover:underline disabled:opacity-60">{resendSaving ? t("email.sending") : t("email.resend")}</button></div>{resendMessage && <div className="mt-1 text-[12px] text-emerald-700 font-sans">{resendMessage}</div>}{resendError && <div className="mt-1 text-[12px] text-[var(--error)] font-sans break-words">{resendError}</div>}</div></div>}<div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="block"><span className="text-[12px] font-medium text-[var(--text-secondary)] font-sans">{t("email.newEmail")}</span><input type="email" value={newEmail} onChange={(event) => onNewEmailChange(event.target.value)} className="mt-1 w-full rounded-md border border-[var(--border-default)] bg-[var(--bg-surface)] px-3 py-2 text-[14px] text-[var(--text-secondary)] font-sans" /></label><label className="block"><span className="text-[12px] font-medium text-[var(--text-secondary)] font-sans">{t("email.confirmPassword")}</span><input type="password" value={emailPassword} onChange={(event) => onEmailPasswordChange(event.target.value)} className="mt-1 w-full rounded-md border border-[var(--border-default)] bg-[var(--bg-surface)] px-3 py-2 text-[14px] text-[var(--text-secondary)] font-sans" /></label></div><div className="mt-4 flex items-center gap-3"><button type="button" onClick={onSave} disabled={emailSaving || newEmail.trim().length === 0 || emailPassword.trim().length === 0} className="px-3 py-2 rounded-md text-[12px] font-medium font-sans bg-[var(--text-primary)] text-[var(--bg-primary)] hover:opacity-90 disabled:opacity-60">{emailSaving ? t("security.updating") : t("email.change")}</button><StatusLine message={emailMessage} error={emailError} /></div></section>
}

export function InvitesSettingsSection({ inviteEmail, inviteError, inviteMessage, inviteSaving, invites, invitesError, invitesLoading, revokingInviteID, t, onCreate, onInviteEmailChange, onRevoke }: { inviteEmail: string; inviteError: string | null; inviteMessage: string | null; inviteSaving: boolean; invites: InviteRecord[]; invitesError: string | null; invitesLoading: boolean; revokingInviteID: string | null; t: T; onCreate: () => void; onInviteEmailChange: (value: string) => void; onRevoke: (inviteID: string) => void }) {
  return <section className="bg-[var(--bg-surface)] border border-[var(--border-default)] rounded-lg p-5 sm:p-6"><h2 className="text-[15px] font-semibold text-[var(--text-primary)] font-sans">{t("invites.title")}</h2><p className="mt-1 text-[12px] text-[var(--text-secondary)] font-sans">{t("invites.description")}</p><p className="mt-1 text-[12px] text-[var(--text-muted)] font-sans">{t("invites.warning")}</p><div className="mt-4 flex flex-col gap-3 sm:flex-row sm:items-end"><label className="block flex-1"><span className="text-[12px] font-medium text-[var(--text-secondary)] font-sans">{t("invites.email")}</span><input type="email" value={inviteEmail} onChange={(event) => onInviteEmailChange(event.target.value)} className="mt-1 w-full rounded-md border border-[var(--border-default)] bg-[var(--bg-surface)] px-3 py-2 text-[14px] text-[var(--text-secondary)] font-sans" placeholder={t("invites.placeholder")} /></label><button type="button" onClick={onCreate} disabled={inviteSaving || inviteEmail.trim().length === 0} className="px-3 py-2 rounded-md text-[12px] font-medium font-sans bg-[var(--text-primary)] text-[var(--bg-primary)] hover:opacity-90 disabled:opacity-60">{inviteSaving ? t("invites.sending") : t("invites.send")}</button></div>{inviteMessage && <div className="mt-2 text-[12px] text-emerald-700 font-sans">{inviteMessage}</div>}{inviteError && <div className="mt-2 text-[12px] text-[var(--error)] font-sans">{inviteError}</div>}{invitesLoading ? <p className="mt-4 text-[13px] text-[var(--text-muted)] font-sans">{t("invites.loading")}</p> : invites.length === 0 ? <p className="mt-4 text-[13px] text-[var(--text-muted)] font-sans">{t("invites.empty")}</p> : <div className="mt-4 divide-y divide-[var(--border-subtle)] rounded-md border border-[var(--border-default)]">{invites.map((invite) => <div key={invite.id} className="flex items-center justify-between gap-3 px-3 py-2"><div><div className="text-[13px] text-[var(--text-primary)] font-medium font-sans">{invite.email}</div><div className="text-[11px] text-[var(--text-muted)] font-sans">{t("invites.expires", { status: invite.status, date: new Date(invite.expires_at).toLocaleDateString() })}</div></div>{invite.status === "pending" ? <Button type="button" variant="outline" size="sm" onClick={() => onRevoke(invite.id)} disabled={revokingInviteID === invite.id}>{revokingInviteID === invite.id ? t("invites.revoking") : t("invites.revoke")}</Button> : <span className="text-[11px] text-[var(--text-muted)] font-sans uppercase tracking-wide">{invite.status}</span>}</div>)}</div>}{invitesError && <div className="mt-2 text-[12px] text-[var(--error)] font-sans">{invitesError}</div>}</section>
}

export function ResourceLinksSection({ t }: { t: T }) {
  const links = [{ href: "/guidelines", label: t("resources.guidelines") }, { href: "/ai-stance", label: t("resources.aiStance") }, { href: "/fairness", label: t("resources.fairness") }, { href: "/about", label: t("resources.about") }, { href: "/transparency", label: t("resources.transparency") }]
  return <section className="bg-[var(--bg-surface)] border border-[var(--border-default)] rounded-lg p-5 sm:p-6"><h2 className="text-[14px] font-semibold text-[var(--text-primary)] font-sans mb-3">{t("resources.title")}</h2><div className="flex flex-wrap gap-x-6 gap-y-2">{links.map((link) => <Link key={link.href} href={link.href} className="text-[13px] font-sans text-[var(--text-secondary)] hover:text-[var(--text-primary)] transition-colors">{link.label}</Link>)}</div></section>
}
